name: Deploy FastAPI App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker
        run: |
          sudo apt update
          sudo apt install -y docker.io
          sudo systemctl start docker

      - name: Build and run container
        run: |
          docker build -t fastapi-app .
          docker stop fastapi-app || true
          docker rm fastapi-app || true
          docker run -d -p 8000:8000 --name fastapi-app fastapi-app
