name: Deployment Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH and Deploy
        env:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          EC2_PUBLIC_IP: ${{ secrets.EC2_PUBLIC_IP }}
          EC2_USER: ubuntu
        run: |
          echo "$SSH_PRIVATE_KEY" > private_key.pem
          chmod 600 private_key.pem
          ssh -o StrictHostKeyChecking=no -i private_key.pem $EC2_USER@$EC2_PUBLIC_IP << 'EOF'
            # Ensure the repository is cloned properly
            if [ ! -d "fastapi-app" ]; then
              git clone https://github.com/alagbaski/fastapi-book-project.git fastapi-app
            fi
            
            cd fastapi-app

            # Pull the latest changes
            git pull origin main

            # Ensure Docker and Docker Compose are installed
            sudo apt update
            sudo apt install -y docker.io docker-compose

            # Use the correct command for docker-compose
            docker-compose down
            docker-compose up --build -d

            # Restart Nginx to apply changes
            sudo systemctl restart nginx
          EOF
