name: Deploy FastAPI App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker
        run: |
          sudo apt-get update
          sudo apt-get remove -y containerd containerd.io docker-ce docker-ce-cli || true
          sudo apt-get autoremove -y
          sudo apt-get clean
          curl -fsSL https://get.docker.com | sudo sh
          sudo systemctl start docker
          sudo systemctl enable docker
          docker --version

      - name: Deploy FastAPI App
        run: |
          docker build -t my-fastapi-app .
          docker run -d -p 8000:8000 my-fastapi-app
