name: Deploy FastAPI App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Debug SSH Key
        run: |
          if [[ -z "${{ secrets.AWS_SSH_PRIVATE_KEY }}" ]]; then
            echo "AWS_SSH_PRIVATE_KEY is empty"
            exit 1
          else
            echo "AWS_SSH_PRIVATE_KEY is set"
          fi

      - name: Set up SSH Key
        run: |
          mkdir -p ~/.ssh
          printf "%s" "${{ secrets.AWS_SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 400 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.AWS_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy FastAPI to EC2
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ubuntu@${{ secrets.AWS_HOST }} << 'EOF'
            # Stop and remove existing container
            docker stop fastapi-app || true
            docker rm fastapi-app || true

            # Pull the latest code
            cd ~/my-fastapi-app
            git pull origin main

            # Build and run FastAPI in a Docker container
            docker build -t my-fastapi-app .
            docker run -d --name fastapi-app -p 8000:8000 my-fastapi-app
          EOF
